# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "53929707c300fad0838e10aed2cf2706"
name = "growing-transaction-app"
handle = "growing-transaction-app-6"
application_url = "https://connect-regional-intense-eyed.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://connect-regional-intense-eyed.trycloudflare.com/auth/callback",
  "https://connect-regional-intense-eyed.trycloudflare.com/auth/shopify/callback",
  "https://connect-regional-intense-eyed.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false

[build]
dev_store_url = "kartikeys-shop.myshopify.com"
automatically_update_urls_on_dev = true
